### PR TITLE
Fix #6

### LINKED ISSUE #6: Fix snake-snake collisions
Right now P1 and P2 pass right through each-other. What is this, the GHOST SNAKE GAME?

I'm not sure what a fair way to deal with the "who dies" question is. I'd say if it's head-on, both snakes die... otherwise, whoever was hit in the tail gets to live another day.

### PR DESCRIPTION
**Pull request by mshenfield**
Hey I liked your game and am thinking about making it into a socket.io based multiplayer app called snakepit so I can play with my friends.  Appreciated the good issues.

### CODE REVIEW

**Comment by rileyjshaw** [comment]
This looks great!!! Thanks for the patch :)

An online-multiplayer mode sounds awesome. I've got a simple socket.io gameserver in [this project](https://github.com/rileyjshaw/tic-attack-toe/blob/master/server.js) if you're interested... it's a bit messy if memory serves, but it got the job done.

I added a few comments to the pull request, if you could clean up that tiny issue and squash the commit I'll merge it right away.

Snakepit is such an awesome name.. :smile:

**Comment by rileyjshaw** [comment]
(Also, just curious: how did you come across this game?)

**Comment by mshenfield** [comment]
Thanks! I'll apply the changes and send it up.

I was looking at CodePen and your Brute's and Bullys simulation popped up.
I liked it and wanted to see what else you had done - and stumbled across
2p-snake.  I'll definitely check out the example project. Haha thanks -
Medusa was another frontrunner - I'm still open to suggestions too.

**Comment by rileyjshaw** [comment]
:heart_decoration: Medusa as well

**Comment by mshenfield** [comment]
Cleaned up and should be good to go

**Comment by rileyjshaw** [comment]
:+1: :+1: :+1: :+1: :+1:

**Pull request merged**
